### ISSUE TITLE
Hang out due to auto-refreshing stale OAuth token when using a service account

### ISSUE THREAD

**Issue by theclue** [cloudyr/googleCloudStorageR#87] opened 2018-03-27 09:25 UTC
Hi,

as the title suggests, when executing the R script to an headless server, triggering an upload the connection hangs due to refreshing token.

AFAIK, this should not happen since I'm using a service account correctly authenticated using a json credential file. Ofc, since it's an headless machine, I cannot open a browser to authenticate the token, there.

I've also tried connecting manually using the gar_auth_service, but this didn't solve the issue

**Comment by MarkEdmondson1234** [comment] 2018-03-27 09:46
Thats odd, is it perhaps you have a token cache file in the directory present?  Could I see some code that is running on the VM? Its probably most easily solved if you set up [auto authentication](http://code.markedmondson.me/googleCloudStorageR/articles/googleCloudStorageR.html#auto-authentication) as that has first authentication priority

**Comment by theclue** [comment] 2018-03-27 12:26
Yes I have (I connect to facebook api using facebook.S4 package on the same script), but this never was a issue.

I used auto athentication at first, it was my first wat to authenticate. I switched to explicitely call gar_auth_service just after.

The weirdest thing is that if I execute the script interactively (in RStudio) and I STOP the hanging call, if I immediately after retry ythe call to gcs_upload, it works seamlessy!

**Comment by MarkEdmondson1234** [comment] 2018-03-27 12:26
Ah ok, in that case its an incompatibility error - I think the httr default cache file name needs to be changed when calling GCS, otherwise it thinks the FB '.httr-oauth` should hold GCS details and tried to re-auth when it only finds Facebook auth details.

You can change the GCS token by specifying it in the `gcs_auth("gcs.oauth")` if you are using that, or if you are not perhaps use `options(googleAuthR.httr_oauth_cache = "gcs.oauth")`

**Comment by MarkEdmondson1234** [comment] 2018-03-27 12:28
It probably works after you retry the hanging call as the GCS cache file is redefined when you run it.  I guess after you do a Facebook API call it hangs again.

**Comment by vhmedina** [comment] 2018-06-11 03:38
Hey,
I'm also having this issue after approx 60 minutes. The error is 

```
Auto-refreshing stale OAuth token.
Request failed [408]. Retrying in 1.4 seconds...
Request failed [408]. Retrying in 1 seconds...
2018-06-10 23:28:28> Request Status Code: 408
Error : lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang=en> 
                     (right here) ------^

Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang=en> 
                     (right here) ------^
In addition: Warning message:
No JSON content found in request 
```
I don't have any .httr-oauth and I have also tried with Mark's suggestions without any success. If you any other idea would be great! Thanks

**Comment by MarkEdmondson1234** [comment] 2018-06-18 11:56
I replicated this today so am looking through it.

**Comment by JamesHydeKing** [comment] 2018-08-21 08:58
Hi @MarkEdmondson1234, I've come across the same issue with the auth token attempting a refresh. Is there now a solution for handling this?

**Comment by MarkEdmondson1234** [comment] 2018-08-21 09:06
The issue will be if the clientid  changes between authentication and upload, could you confirm if that happens in your case using the options above? Place it right before the upload code.

**Comment by JamesHydeKing** [comment] 2018-08-21 09:49
Added the above but client_secret is NULL. I'm authenticating with a JSON file. Code looks something like this. Am I missing something here?

```
Sys.setenv("GCS_AUTH_FILE"="XXXXXXXXXX.json")

library(googleCloudStorageR)

client_secret <- getOption("googleAuthR.client_secret")

print(client_secret)
```

Output

```
Setting scopes to https://www.googleapis.com/auth/devstorage.full_control
Successfully authenticated via XXXXXXXXXX.json
NULL
```

**Comment by benny-hal** [comment] 2018-08-22 11:40
I have this exact issue, whenever there is 60 mins between calling the API. I am happy to help provide more details, what do u need to know?

**Comment by MarkEdmondson1234** [comment] 2018-08-24 07:02
This doesn’t happen with other googleAuthR libraries so I need to look through and see what’s happening.

**Comment by MarkEdmondson1234** [comment] 2018-08-24 15:28
Can I check what versions people are using?  But regardless, I have uploaded a new version to github that greatly simplifies authentication but has no default client ID set - so you will need to make sure you set your own with `googleAuthR::gar_set_client()` - however I think this should mean less confusing errors when it attempts to authentication with another Cloud project.  I will need to update the documentation but basically it favours you downloading the auth service json file and putting it in the `GCS_AUTH_FILE` environment argument as most people do anyhow.

**Comment by benny-hal** [comment] 2018-08-26 12:45
the new changes did not seem to help, this is the printout I got after 60 mins

options(googleAuthR.scopes.selected=c('https://www.googleapis.com/auth/devstorage.full_control'))
options(googleAuthR.client_id='.....')
options(googleAuthR.client_secret=' ....')
2018-08-26 12:41:46 -- File size detected as 282.4 Kb
Auto-refreshing stale OAuth token.

**Comment by MarkEdmondson1234** [comment] 2018-08-26 19:04
If you are using the GitHub version, it should be that only JSON authentication is possible, so no token to refresh - please delete any `.httr-oauth` and otherwise tokens in your directory if they are there and start with a fresh slate. Can I confirm this is the case before taking another look at it?

**Comment by michaelhogersosis** [comment] 2019-06-25 11:43
Has this issue been solved already @MarkEdmondson1234 ?

**Comment by ammadrigal** [comment] 2019-06-28 14:45
Hello, was there any way to fix this issue? Im having the same problem. Have an R process which runs in GCP... I set the Sys.setenv("GCS_AUTH_FILE" = "./XXXXXX.json") at the start of the code together with Sys.setenv("GCS_DEFAULT_BUCKET" = "xxxxxxx").... at the end of the code I upload results to GCS... when data is not huge, I guess it runs within access expiring and I had no problems.. But when full process takes longer, then it hangs and I get the same error stated above.
Reding this, I tried to repeat the line: Sys.setenv("GCS_AUTH_FILE" = "./XXXXXX.json") before my upload to GCS, but it is still hanging... any other ideas(?)
Any help appreciated.

**Comment by MarkEdmondson1234** [comment] 2019-06-28 17:55
Its cleared up for me, are you using the GitHub version?  I think it was to do with the scopes being changed in-between authentication and upload.  The general cloud scopes should be used instead for everything.

Are you using other API calls in the same script that may be overwriting the token?

If you can put a reproducible example that will help a lot to pin this down.

**Comment by ammadrigal** [comment] 2019-06-29 00:17
Hello! Thanks for replying... 

I'm attaching a script which doesnt reproduce error, but shows some explanations and background, my code structure and main lines interacting with GCP. Although quite experienced with R, I feel out of my league re:GCP, just learned basics to be able to set this up.. It has been working fine for some months, now an issue with a particular data, but as far as I can tell is not a data issue. All fine up to line 121 in this flle... issue at line 123
[CodeExampleToFindSolution.txt](https://github.com/cloudyr/googleCloudStorageR/files/3341213/CodeExampleToFindSolution.txt)


At the moment of writing this, using version 0.4.0 of googleCloudStorageR package from CRAN.

I dont use any other APIs in the same script... 

Here some background (also in main attached file) of why this is puzzling...

#Background: There are 2 versions of the masterScript (mS): Both produce basically the same calcs... 
mS.A: produces about 5 different outputs between xlsx , pdf, csv, html... and stores some more columns than B
mS.B: produces only one or two of the xlsx outputs produced with mS.A and with less columns in the different tabs, so smaller in size. But script B is basically the same as A with less gcs_upload() calls

#There are input data sources of different sizes in csv format, between 1-15 million rows and also different complexity depending on n_distinct values in one of the variables... so not necessarily the longer the row-size, the longer time it takes to finish the process.

#Puzzling as: Script works well up to end for mS.A for all data tested.
#-----------: Script works well up to end for mS.B for all but one data Set.
#-----------: Script doesn't work for mS.B for one data Set, which is more complex than the other data. 
#-----------: It does work well upto creating the xlsx output file locally. 

#General set-up: input files live in GCStorage within a GCP project. Main code and functions also in GCS.
#there is an outputDir in GCS where output is uploaded at the end from VM. 
#VM with an image from docker file containg RStudio and loading packages from CRAN: 
#at the moment of writing this, it loads at the moment version 0.4.0 of googleCloudStorageR package.
#final user uploads json file and startScript and puts to run the startScript. Waits. When finished, they close VM and output in GCS (normally)

**Comment by MarkEdmondson1234** [comment] 2019-06-29 07:07
Ok first reaction is to use the GitHub version if possible, that insets some defaults that may effect upload. I’ll take a closer look at the script.


________________________________

**Comment by ammadrigal** [comment] 2019-06-29 10:17
Thanks.... for version stability of the rest of the process, docker file was fix to use R 3.5.1
I get the next lines after trying to install the git version in the session using your lines (?) Sorry, this might be a silly question... with a quick workaround..
> ## install some  extra packages: later on they can be added to docker File.
> if(!require("ghit")){
+   install.packages("ghit")
+ }
Loading required package: ghit
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘ghit’ is not available (for R version 3.5.1)
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘ghit’

**Comment by MarkEdmondson1234** [comment] 2019-06-29 11:18
I use library(remotes) for github installs eg remotes::install_github()


________________________________

**Comment by ammadrigal** [comment] 2019-06-30 10:01
Hello,
I installed from github version 0.4.0.9000, for which I also had to update googleAuthR to 0.7.0 from 6.3, but it is still not working. The new feature is that I found a pop-up blocked which was not there before
<img width="375" alt="Screen Shot 2019-06-30 at 10 52 06" src="https://user-images.githubusercontent.com/8194297/60395096-3adaef80-9b26-11e9-9d14-a4503cc5ba93.png">

but same error found:
Auto-refreshing stale OAuth token.
Request failed [408]. Retrying in 1 seconds...
Request failed [408]. Retrying in 2.5 seconds...
2019-06-29 20:21:34> Request Status Code: 408
Error : lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang=en> 
                     (right here) ------^

any other ideas?

**Comment by MarkEdmondson1234** [comment] 2019-06-30 10:11
Yes I think that helps a bit, it indicates a manual authentication is being attempted and not service auth. Eg using gar_auth() instead of gar_auth_service() - will see if it’s code doing this but also check your script that only service auth is being attempted.


________________________________

**Comment by MarkEdmondson1234** [comment] 2019-06-30 10:13
As it’s attempting refresh at all indicates service auth is not being used which doesn’t do that.


________________________________

**Comment by ammadrigal** [comment] 2019-06-30 12:25
I managed to reproduce the error with a smaller subset of the data, so at least debugging is faster. It runs in less than 60 minutes so not really problem with going after an hour. I managed to make it to run by deleting the "it" in the name (files are stamped with the original data file name and this data had a "wittchen" in the name...)... I am now testing the bigger version and will let you know if that made a difference  - I hope it does... Still puzzled about  why it would run with mS.A version with the original name, as if the "it" was an issue it will be in both cases , I would presume... but as I am fishing for solutions, it is worth trying... I'll let you know if that worked...

**Comment by ammadrigal** [comment] 2019-06-30 13:38
Mmm.. no... sorry, that was a red-herring.. still breaking.. no clue...

**Comment by MarkEdmondson1234** [comment] 2019-06-30 14:38
Ok so the issue is you aren't actually authenticating with the service JSON, but with a user based token e.g. delete any `.httr-oauth` tokens in your folder and retry with JSON auth.

**Comment by ammadrigal** [comment] 2019-06-30 17:37
Thanks for your help... I think I'll need to do a bit more reading about this as I'm out of my league in here and cannot see the .httr-oauth file... I've seen it is a hidden file in my working directory... will try to find it as it is hidding very well... 
<img width="1205" alt="Screen Shot 2019-06-30 at 18 24 50" src="https://user-images.githubusercontent.com/8194297/60400026-17d03000-9b66-11e9-8253-cc54c6122999.png">

**Comment by michaelhogersosis** [comment] 2019-07-01 07:23
> Its cleared up for me, are you using the GitHub version? I think it was to do with the scopes being changed in-between authentication and upload. The general cloud scopes should be used instead for everything.
> 
> Are you using other API calls in the same script that may be overwriting the token?
> 
> If you can put a reproducible example that will help a lot to pin this down.

My previous post lacked a bit of a description. First of all, thanks a lot for this package, it is of incredible value to our projects.

We are using googleCloudStorageR in a Shiny application. From what we noticed this issue only happens when sessions last for longer than 30/60 minutes. 

Our application sets the environment variables GCS_AUTH_FILE and GCS_DEFAULT_BUCKET in global.R. In server.R we have the following logic flow for googleCloudStorageR: 
`library(googleCloudStorageR)`   
`googleAuthR::gar_auth_service(Sys.getenv('GCS_AUTH_FILE'), scope = getOption("googleAuthR.scopes.selected"))` 
 `googleCloudStorageR::gcs_global_bucket(Sys.getenv('GCS_DEFAULT_BUCKET'))`

We have now added a reactiveTimer that refreshes the token every 30 minutes, with the following line:
       ` googleAuthR::gar_auth_service(Sys.getenv('GCS_AUTH_FILE'), scope = getOption("googleAuthR.scopes.selected"))`

**Comment by MarkEdmondson1234** [comment] 2019-07-01 10:17
First thing is to install the development version if you can, as it has this NEWs entry:
https://github.com/cloudyr/googleCloudStorageR/blob/master/NEWS.md

* Refactor authentication to favour json file and fix auth hangs (#87)

`remotes::install_github("cloudyr/googleCloudStorageR")`

**Comment by michaelhogersosis** [comment] 2019-07-01 10:19
Thanks Mark. I mistakenly assumed we already used the dev version, cheers.

**Comment by MarkEdmondson1234** [comment] 2019-07-02 08:20
Great - @ammadrigal can you confirm if the above works for you too? (e.g. you need to update to latest GitHub version to stop the hangs).  If you and @michaelhogersosis confirm it fixes it then I'll mark this closed.

**Comment by michaelhogersosis** [comment] 2019-07-02 08:24
I will use the development version in our application, if it occurs again over the coming days I will let you know. Thanks @MarkEdmondson1234

**Comment by ammadrigal** [comment] 2019-07-02 08:41
Hello, Thanks for keeping an eye on us!
At the moment behaviour is erratic. As Michael, I’ll let you know if final user notices anything in the next days. 
@MarkEdmondson1234

**Comment by MarkEdmondson1234** [comment] 2019-07-02 09:18
@ammadrigal are you using googleCloudStorageR version 0.4.0.9000 ?

**Comment by ammadrigal** [comment] 2019-07-02 12:59
I’m testing both options. But if I use the GitHub one, 0.4.0.9000 , the pop-up comes up, and couldn’t follow instructions of the .httr file, because there is none in my working directory... one time it worked was with changing name of output file... still puzzled. But now they are testing with more data and I’ll keep you posted.

**Comment by ammadrigal** [comment] 2019-07-02 13:00
I saw a similar error ( about refreshing auth) when one of my team was trying to load a file that didn’t exist in the GCS as he wrote wrong name... so it is possibly nothing wrong from your package/side..(?)

**Comment by MarkEdmondson1234** [comment] 2019-07-30 12:18
With the new `gargle` backend to googleAuthR this should be solved, please reopen in another issue with an example if you come across it again.

**Closed by MarkEdmondson1234** 2019-07-30 12:18 UTC
